package client;

import java.io.Serializable;
import java.util.Random;
import java.util.Vector;

public interface Widget extends Serializable{
	
	//This instruction needs to return a new instance of the widget that can be used
	//to generate a new instruction.
	public Widget getRandomInstruction();
	
	//Returns a string that is an instruction for how to change this widget, assuming this was
	//generated by the previous function
	public String getInstructionString();
	
	//Compares another widget to check if it is the same one.  This is used to check if the instruction matches the
	//changed widget
	public boolean equals(Object other);
	
	//Updates the widget to a new value given the current one
	public void update(Widget w);
	
	//Gets the name of the widget
	public String getName();
	
}

abstract class SingleButtonPress implements Widget{
	private static final long serialVersionUID = 251334623591367419L;
	protected String name;
	protected int buttons;
	protected int val;
	
	public SingleButtonPress(String name, int buttons, int val){
		this.name = name;
		this.buttons = buttons;
		this.val = val;
	}
	
	public String getName(){
		return name;
	}
	
	public int getVal(){
		return this.val;
	}
	
	public boolean equals(Object other){
		if (other instanceof SingleButtonPress){
			if (((SingleButtonPress) other).getVal() == this.val){
				if (((SingleButtonPress) other).getName() == this.name){
					return true;
				}
			}
		}
		return false;
	}
	
	public void update(Widget w){
		//This function doesn't matter because the button press means we don't need to store the value
	}
	
}

abstract class SingleValueWidget implements Widget{
	//Base class for any widget which only have one value out of a collection
	private static final long serialVersionUID = -1921593644005787609L;
	protected String name;
	protected int val;
	protected int min;
	protected int max;
	
	public SingleValueWidget(String name, int min, int max, int init_val){
		this.name = name;
		this.val = init_val;
		this.min = min;
		this.max = max;
	}
	
	public String getName(){
		return this.name;
	}
	
	public int getVal(){
		return this.val;
	}
	
	public void setVal(int i){
		val = i;
	}
	
	public void update(Widget w){
		if (w instanceof SingleValueWidget){
			SingleValueWidget widget = (SingleValueWidget) w;
			this.val = widget.getVal();
		}
	}
	
	public boolean equals(Object other){
		if (other instanceof SingleValueWidget){
			SingleValueWidget w = (SingleValueWidget) other;
			if (w.getName().equals(this.getName())){
				if (w.getVal() == this.getVal()){
					return true;
				}
			}
		}
		return false;
	}
	
}

class Slider extends SingleValueWidget{

	private static final long serialVersionUID = 2467286323078940573L;

	public Slider(String name, int min, int max, int init_val) {
		super(name, min, max, init_val);
	}

	public Widget getRandomInstruction() {
		Random r = new Random();
		int random_init = r.nextInt(max - min) + min;
		while(random_init == val){
			random_init = r.nextInt(max - min) + min;
		}
		return new Slider(this.name, this.min, this.max, random_init);
	}
	
	public void setVal(int i){
		val = i;
	}
	public String getInstructionString() {
		return String.format("Set %s to %d", this.name, this.val);
	}
	
}

//Dashboard1_1
class TransmissionWidget extends SingleValueWidget{

	private static final long serialVersionUID = -8736650004890706239L;

	public TransmissionWidget(int init_val) {
		super("Transmission", 0, 2, init_val);
	}

	@Override
	public Widget getRandomInstruction() {
		if (val == 0){
			return new TransmissionWidget(1);
		}
		else{
			return new TransmissionWidget(0);
		}
	}

	@Override
	public String getInstructionString() {
		if (val == 0){
			return "Set Transmission to Automatic";
		}
		else{
			return "Set Transmission to Manual";
		}
	}
	
}

class CrowleyCoke extends SingleButtonPress{
	private static final long serialVersionUID = -5357064506459382322L;
	public CrowleyCoke() {
		super("Crowley Coke", 1, 0);
	}
	public Widget getRandomInstruction(){
		return new CrowleyCoke();
	}
	public String getInstructionString(){
		return "Refill Crowley's Coke Cup";
	}
	
}

class Mosfet extends SingleButtonPress{
	private static final long serialVersionUID = -6910617819805233446L;
	public Mosfet(int init){
		super("Mosfet", 2, init);
	}
	public Widget getRandomInstruction() {
		return new Mosfet((new Random()).nextInt(buttons));
	}
	public String getInstructionString() {
		switch(val){
		case(1):
			return "Set the MOSFET to N-CHANNEL";
		default:
			return "Set the MOSFET to P-CHANNEL";
		}
	}
}

//Dashboard 1_2
class SpaceGate extends SingleButtonPress{
	private static final long serialVersionUID = -156256557296860257L;
	public SpaceGate(int val) {super("Space Gate", 2, val);}
	public Widget getRandomInstruction() {
		return new SpaceGate((new Random().nextInt(buttons)));
	}

	public String getInstructionString() {
		switch(val){
		case(0):
			return "Open the Space Gate";
		default:
			return "Close the Space Gate";
		}
	}
}
class Nextron extends SingleButtonPress{
	private static final long serialVersionUID = -2028498420433459612L;
	public Nextron(){super("Nextron", 1, 0);}
	public Widget getRandomInstruction(){
		return new Nextron();
	}
	public String getInstructionString(){return "Reset the Nextron";}
}
class FluxCapacitor extends SingleValueWidget{
	private static final long serialVersionUID = -3674135814018327313L;
	public FluxCapacitor(int init_val) {
		super("Flux Capacitor", 0, 2, init_val);
	}
	public Widget getRandomInstruction() {
		if (val == 0){
			return new FluxCapacitor(1);
		}
		else{
			return new FluxCapacitor(0);
		}
	}
	public String getInstructionString() {
		if (val == 0){
			return "Set Flux Capacitor to Clean";
		}
		else{
			return "Set Flux Capacitor to Venting";
		}
	}
}

//Dashboard 1_3
class CoffeeMaker extends SingleButtonPress{
	private static final long serialVersionUID = 1L;
	public CoffeeMaker(){super("Coffee Maker", 1, 0);}
	public Widget getRandomInstruction(){
		return new CoffeeMaker();
	}
	public String getInstructionString(){return "Brew the Coffee";}
}
class Hitchhiker extends SingleValueWidget{
	private static final long serialVersionUID = -2547599328339340031L;
	public Hitchhiker(int init_val) {
		super("Hitchhiker", 0, 2, init_val);
	}
	public Widget getRandomInstruction() {
		if (val == 0){
			return new Hitchhiker(1);
		}
		else{
			return new Hitchhiker(0);
		}
	}
	public String getInstructionString() {
		if (val == 0){
			return "Allow Hitchhikers";
		}
		else{
			return "Deny Hitchhikers";
		}
	}
}
class GPA extends Slider{
	private static final long serialVersionUID = -7374408602736874755L;
	public GPA(int init_val) {
		super("GPA", 0, 3, 0);
	}
	public String getInstructionString(){
		switch(val){
		case(0):
			return "Set GPA to 2.5";
		case(1):
			return "Set GPA to 3.0";
		case(2):
			return "Set GPA to 3.5";
		default:
			return "Set GPA to 4.0";
		}
	}
	
}
//Dashboard 1_4
class SelfDestruct extends SingleButtonPress{
	private static final long serialVersionUID = -5169146801936305954L;
	public SelfDestruct() {
		super("Self Destruct", 1, 0);
	}
	public Widget getRandomInstruction(){
		return new SelfDestruct();
	}
	public String getInstructionString(){
		return "Activate Self Destruct";
	}
}
class Technograph extends SingleValueWidget{
	private static final long serialVersionUID = -7404621332294188960L;
	public Technograph(int init_val) {
		super("Technograph", 0, 2, init_val);
	}
	public Widget getRandomInstruction() {
		if (val == 0){
			return new Technograph(1);
		}
		else{
			return new Technograph(0);
		}
	}
	public String getInstructionString() {
		if (val == 0){
			return "Set Technograph to high";
		}
		else{
			return "Set Technograph to low";
		}
	}
}
class Flamethrower extends SingleButtonPress{
	private static final long serialVersionUID = -156256557296860257L;
	public Flamethrower(int val) {super("Flamethrower", 2, val);}
	public Widget getRandomInstruction() {
		return new Flamethrower((new Random().nextInt(buttons)));
	}
	public String getInstructionString() {
		switch(val){
		case(0):
			return "Point the Flamethrower";
		default:
			return "Shoot the Flamethrower";
		}
	}
}
//public abstract class Widget implements Serializable {
//	private static final long serialVersionUID = -4298245903822614337L;
//	private Vector<Integer> val;
//	private String name;
//	
//	public Widget(String name){
//		this.setName(name);
//		this.val = new Vector<Integer>();
//	}
//
//
//	public String getName(){
//		return name;
//	}
//
//	public void setName(String name){
//		this.name = name;
//	}
//	
//	public Vector<Integer> getValues(){
//		return val;
//	}
//	
//	public boolean equals(Widget other){
//		return (this.name == other.getName() && this.val.equals(other.getValues()));
//	}
//	
//	public abstract Widget getRandomInstruction();
//	
//	public abstract String getInstructionString();
//	
//}
